services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  customers.api:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: Customers.Api/Dockerfile
