services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
        SA_PASSWORD: "Password123"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
        TZ: Europe/Madrid
    ports:
      - "1434:1433"
    volumes:
      - C:/volumes/data/:/var/opt/mssql/data
      - C:/volumes/log/:/var/opt/mssql/log
      - C:/volumes/secrets/:/var/opt/mssql/secrets

  customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Customers;User Id=sa;Password=Password123;TrustServerCertificate=true
    ports:
      - "5050:8080"
      - "5051:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro